name: learn-github-actions
on: [push]
jobs:
  e2e-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello World"
      - name: Checkout Rocket.Chat
        uses: actions/checkout@v2
        with:
          repository: RocketChat/Rocket.Chat
          ref: 'develop'
          token: ${{ secrets.GTHUB_PAT }}
          path: RocketChat
      - name: Checkout Apps-Engine
        uses: actions/checkout@v2
        with:
          repository: RocketChat/Rocket.Chat.Apps-engine
          token: ${{ secrets.GTHUB_PAT }}
          path: Apps-Engine
      - name: Show Working Directory
        run: ls
      - name: Show Working Directory Structure
      - run: tree