name: learn-github-actions
on: [push]
jobs:
  e2e-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - uses: meteorengineer/setup-meteor@v1
      - name: Checkout Rocket.Chat
        uses: actions/checkout@v2
        with:
          repository: RocketChat/Rocket.Chat
          ref: 'develop'
          token: ${{ secrets.GTHUB_PAT }}
          path: Rocket.Chat
      - name: Checkout Apps-Engine
        uses: actions/checkout@v2
        with:
          repository: RocketChat/Rocket.Chat.Apps-engine
          token: ${{ secrets.GTHUB_PAT }}
          path: apps-engine
      - run: npm install
        working-directory: $GITHUB_WORKSPACE/apps-engine
      - run: npm run compile
        working-directory: $GITHUB_WORKSPACE/apps-engine
      - run: meteor npm install
        working-directory: $GITHUB_WORKSPACE/Rocket.Chat
      - run: rm -r $GITHUB_WORKSPACE/Rocket.Chat/node_modules/@rocket.chat/apps-engine
      - run: ln -s $GITHUB_WORKSPACE/apps-engine $GITHUB_WORKSPACE/Rocket.Chat/node_modules/@rocket.chat/apps-engine
      - run: meteor npm start
        working-directory: $GITHUB_WORKSPACE/Rocket.Chat